# Generated by Django 5.2.10 on 2026-01-29 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'Phone Number already exists.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0789540636'", regex='^\\+?1?\\d{10}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STAFF', 'Staff Member'), ('ADMIN', 'Administrator'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
