# Generated by Django 5.2.10 on 2026-01-29 13:37

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='productmedia',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', validators=[products.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/', validators=[products.models.validate_video_size]),
        ),
    ]
